version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${USER_NAME}
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 200M
        reservations:
          cpus: '1'
          memory: 200M
    volumes:
      - ./postgres:/var/lib/postgresql/data
