version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - '${PORT_DB}:5432'
    environment:
      - POSTGRES_PASSWORD=${PASSWORD_DB}
      - POSTGRES_DB=${NAME_DB}
      - POSTGRES_USER=${USER_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data"
